import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav/nav-bar";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/theme/theme-toggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" suppressHydrationWarning>
      <body className="md:bg-gradient-to-r  from-[hsl(191,95%,45%)] to-[hsl(210,90%,40%)] overflow-hidden">
        <div className="m-3 rounded-xl bg-secondary h-[97vh]">
          <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
              <div className="h-full w-full">
                <NavBar />
                {children}
              </div>
            </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
